# SPDX-License-Identifier: GPL-2.0-or-later
include("${SOURCE_ROOT}/cmake/common/dependency-version.cmake")
file(READ "${SOURCE_ROOT}/buildspec.json" manifest)
foreach(name IN ITEMS obs-studio prebuilt qt6)
  string(JSON data GET "${manifest}" dependencies ${name})
  obs3dgs_dependency_version("${data}" macos mac_version)
  obs3dgs_dependency_version("${data}" windows-x64 win_version)
  if(name STREQUAL obs-studio)
    set(expected_mac 32.1.2)
    set(expected_win 32.2.2)
  else()
    set(expected_mac 2025-08-23)
    set(expected_win 2026-07-15)
  endif()
  if(NOT mac_version STREQUAL expected_mac OR NOT win_version STREQUAL expected_win)
    message(FATAL_ERROR "${name}: platform SDK selection drifted")
  endif()
endforeach()
obs3dgs_dependency_version([[{"version":"1.0"}]] macos legacy)
if(NOT legacy STREQUAL "1.0")
  message(FATAL_ERROR "Manifests without overrides must keep their common version")
endif()
message(STATUS "Platform dependency selection passed")
